version: '3.3'
services:
    nginx:
      build:
          context: .
          dockerfile: docker/Nginx.Dockerfile
      ports:
        - 8098:80
      links:
          - fpm
      volumes:
          - ./:/var/www/yii-application
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
          - ./:/var/www/yii-application
        links:
          - mysql
    db:
        image: mysql:latest
        ports:
          - 3306:3306
        volumes:
          - ./docker/dbdata:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=yii-application
