<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $heading
 * @property string $content
 * @property string $short_description
 * @property string|null $image
 * @property string $publication_date
 * @property int|null $category_id
 *
 * @property Category $category
 */
class Post extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['heading', 'content', 'short_description'], 'required'],
            [['content', 'short_description'], 'string'],
            [['publication_date'], 'default', 'value' => date('Y-m-d')],
            [['category_id'], 'integer'],
            [['heading', 'image'], 'string', 'max' => 255],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::class, 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'heading' => 'Heading',
            'content' => 'Content',
            'short_description' => 'Short Description',
            'image' => 'Image',
            'publication_date' => 'Publication Date',
            'category_id' => 'Category ID',
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    /**
     *
     * @return ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::class, ['id' => 'tag_id'])
            ->viaTable('tag_post', ['post_id' => 'id']);
    }

    public function saveFile($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function deleteImage()
    {
        $imageUploadModel = new FileUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getImage()
    {
        return ($this->image) ? '/img/'.$this->image: '';
    }

    public function saveCategory($category_id)
    {
        $this->category_id = $category_id;

        return $this->save(false);
    }

    public function getCurrentTags()
    {
        $currentTags = $this->getTags()->select('id')->asArray()->all();
        return ArrayHelper::getColumn($currentTags, 'id');
    }

    public function getCurrentTagsName()
    {
        $currentTags = $this->getTags()->select('name')->asArray()->all();
        return ArrayHelper::getColumn($currentTags, 'name');
    }


    public function deleteCurrentTags()
    {
        return TagPost::deleteAll(['post_id' => $this->id]);
    }

    public function saveTags($tags)
    {
        $this->deleteCurrentTags();

        if (is_array($tags)){
            foreach ($tags as $tag_id)
            {
                $tag = Tag::findOne($tag_id);
                $this->link('tags', $tag);
            }
        }
    }

}
